begin;

create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code ~ '^[A-Z0-9][A-Z0-9_-]{2,31}$'),
  kind text not null check (kind in ('percentage', 'fixed', 'final_total')),
  amount integer not null check (
    (kind = 'percentage' and amount between 1 and 99)
    or (kind in ('fixed', 'final_total') and amount between 25 and 1000000000)
  ),
  description text not null default '' check (char_length(description) <= 200),
  active boolean not null default false,
  min_subtotal_cents integer not null default 0 check (min_subtotal_cents between 0 and 1000000000),
  max_uses integer check (max_uses between 1 and 1000000),
  uses_count integer not null default 0 check (uses_count >= 0),
  starts_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  check (starts_at is null or expires_at is null or expires_at > starts_at)
);

alter table public.coupons enable row level security;
revoke all on public.coupons from public, anon, authenticated;
grant all on public.coupons to service_role;

alter table public.orders
  add column if not exists coupon_id uuid references public.coupons(id),
  add column if not exists coupon jsonb,
  add column if not exists discount_cents integer not null default 0;

-- PostgreSQL may name the original multi-column check orders_check. Match its
-- exact expression rather than depending on an autogenerated constraint name.
do $$
declare original_check record;
begin
  for original_check in
    select conname from pg_catalog.pg_constraint
    where conrelid = 'public.orders'::regclass and contype = 'c'
      and regexp_replace(pg_catalog.pg_get_constraintdef(oid), '[[:space:]()]', '', 'g')
        = 'CHECKtotal_cents=subtotal_cents+shipping_cents'
  loop
    execute format('alter table public.orders drop constraint %I', original_check.conname);
  end loop;
end;
$$;
alter table public.orders drop constraint if exists orders_total_after_coupon_check;
alter table public.orders add constraint orders_total_after_coupon_check check (
  discount_cents >= 0
  and total_cents > 0
  and total_cents::bigint = subtotal_cents::bigint + shipping_cents::bigint - discount_cents::bigint
);

create or replace function public.commerce_apply_coupon() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  selected_coupon public.coupons;
  expected_snapshot jsonb;
  gross_cents bigint;
  requested_discount bigint;
  expected_discount bigint;
  checked_at timestamptz;
begin
  if new.coupon_id is null then
    if new.coupon is not null or new.discount_cents is distinct from 0 then
      raise exception 'coupon_snapshot_mismatch';
    end if;
    return new;
  end if;

  -- Serialize competing checkouts for the same coupon. The counter increment
  -- rolls back with the INSERT if its UUID/idempotency/quote constraint fails.
  select * into selected_coupon from public.coupons
    where id = new.coupon_id for update;
  checked_at := clock_timestamp();
  if not found or not selected_coupon.active
    or (selected_coupon.starts_at is not null and selected_coupon.starts_at > checked_at)
    or (selected_coupon.expires_at is not null and selected_coupon.expires_at <= checked_at)
    or new.subtotal_cents < selected_coupon.min_subtotal_cents
    or (selected_coupon.max_uses is not null and selected_coupon.uses_count >= selected_coupon.max_uses)
    or (selected_coupon.kind = 'final_total' and new.subtotal_cents < selected_coupon.amount) then
    raise exception 'coupon_unavailable';
  end if;

  expected_snapshot := jsonb_build_object(
    'code', selected_coupon.code,
    'kind', selected_coupon.kind,
    'amount', selected_coupon.amount
  );
  if new.coupon is distinct from expected_snapshot then
    raise exception 'coupon_snapshot_mismatch';
  end if;

  -- Same integer-cent arithmetic as lib/coupon-validation.ts. Regular coupons
  -- only discount merchandise; final_total also covers the selected freight.
  gross_cents := new.subtotal_cents::bigint + new.shipping_cents::bigint;
  requested_discount := case selected_coupon.kind
    when 'percentage' then (new.subtotal_cents::bigint * selected_coupon.amount::bigint) / 100
    when 'fixed' then selected_coupon.amount::bigint
    else greatest(0::bigint, gross_cents - selected_coupon.amount::bigint)
  end;
  expected_discount := least(requested_discount,
    greatest(0::bigint,
      (case when selected_coupon.kind = 'final_total' then gross_cents else new.subtotal_cents::bigint end) - 25
    )
  );
  if new.discount_cents::bigint is distinct from expected_discount
    or new.total_cents::bigint is distinct from gross_cents - expected_discount
    or new.total_cents < 25 then
    raise exception 'coupon_amount_mismatch';
  end if;

  update public.coupons set uses_count = uses_count + 1 where id = selected_coupon.id;
  return new;
end;
$$;
revoke all on function public.commerce_apply_coupon() from public, anon, authenticated;
grant execute on function public.commerce_apply_coupon() to service_role;
drop trigger if exists commerce_apply_coupon on public.orders;
create trigger commerce_apply_coupon before insert on public.orders
for each row execute function public.commerce_apply_coupon();

-- One registered order consumes one use, including an unpaid or cancelled
-- order. Reapplying this migration never restores uses or activates it again.
insert into public.coupons (code, kind, amount, description, active, max_uses)
values ('25TESTE', 'final_total', 25, 'Cupom de teste: pedido por R$ 0,25, incluindo o frete selecionado. Uso único.', true, 1)
on conflict (code) do nothing;

notify pgrst, 'reload schema';
commit;
